server {

    # Nginx listens on port 443 with ssl
    listen 443 ssl;

    # server name and the server block that should be used for requests to the server
    server_name zpiarova.42.fr www.zpiarova.42.fr;

    # root directory for requests to the server - /var/www/html is created as mount point at build time by wp Dockerfile and mounts wp files in this volume
    root /var/www/html;

    # define indexed - prioritize index.php when possible
    index index.php index.html;

    # ssl certificates
    ssl_certificate /etc/ssl/fullchain.pem;
    ssl_certificate_key /etc/ssl/privkey.pem;

    # Only allow TLS 1.2 and 1.3
    ssl_protocols TLSv1.2 TLSv1.3;

    # a. general request handler, tries to find uri as static file, directory, and lastly fallback to internally route the request to /index.php which will match the second location block too
    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # b. php requests proxy - when php uri is matched
    location ~ \.php$ {  # ~ means use a regular expression that matchs .php$
        fastcgi_split_path_info ^(.+\.php)(/.+)$; # handle and store URLs where there is additional path information after the PHP filename
        fastcgi_pass wordpress:9000; # proxy requests to php:fpm over fastCGI protocol
        fastcgi_index index.php;  # default php script when directory is passed to FastCGI
        include fastcgi_params; # load predefined fastcgi parameters that communicate HTTP request paramt to PHP-FPM
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;  # provide file path to exeute to wordpress container
        fastcgi_param PATH_INFO $fastcgi_path_info; # pass the additional apth information stored before
    }
}