version: "3.9"

services:
  nginx:
    build:
      context: "./requirements/nginx"
      args: # available only during build
        NGINX_HOST_PORT: ${NGINX_HOST_PORT:-443}
        DOMAIN_NAME: ${DOMAIN_NAME:-zpiarova.42.fr}
    container_name: nginx
    networks:
      - inception-network
    depends_on:
      - wordpress
    ports:
      - "${NGINX_HOST_PORT:-443}:443" # expose to host only this port to get requests from internet
    volumes:
      - ${WORDPRESS_FILE_PATH}:/var/www/html
      # - ./requirements/nginx/conf:/etc/nginx/conf.d # bind nginx conf file
      - ./.secrets/ssl:/etc/ssl # bind certificates
    restart: "on-failure"

  wordpress:
    build: "./requirements/wordpress"
    container_name: wordpress
    networks:
      - inception-network
    depends_on:
      - mariadb
    # no ports because we do not want to expose it to host
    volumes:
      - ${WORDPRESS_FILE_PATH}:/var/www/html # bind dir for site files
    restart: "on-failure"
    environment:
      WORDPRESS_DB_HOST: mariadb:${DB_PORT}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}

  mariadb: 
    build: "./requirements/mariadb"
    container_name: mariadb
    networks:
      - inception-network
    # no ports because we do not want to expose it to host
    volumes:
      - ${WORDPRESS_DB_PATH}:/var/lib/mysql  # bind mount
    restart: "on-failure"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}

# blocks can be empty if we want the default config, compose will create them automatically
networks:
  inception-network: 