version: "3.9"

services:
  nginx:
    build: "./requirements/nginx"
    image: nginx
    container_name: nginx
    networks: # nginx is in both networks since it’s the true bridge
      - frontend
      - backend
    depends_on:
      - wordpress
    ports:
      - "443:443" # only expose this to outside world since we have to get requests from internet
    volumes:
      - wordpress-site:/var/www/html
      - ./requirements/nginx/conf:/etc/nginx/conf.d # bind directory with nginx conf file on host to nginx/conf.d on container, as it should always contain the current conf file
      - ./.keys/ssl:/etc/ssl
    restart: "on-failure"

  wordpress:
    build: "./requirements/wordpress"
    image: wordpress
    container_name: wordpress
    expose:
      - "9000"
    networks:
      - backend
    depends_on:
      - mariadb
    # no ports because we do not want to expose it to host
    volumes:
      - wordpress-site:/var/www/html # bind mount
    restart: "on-failure"
    environment:
      WORDPRESS_DB_HOST: mariadb:${DB_PORT}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WORDPRESS_USER: ${WORDPRESS_USER}
      WORDPRESS_USER_EMAIL: ${WORDPRESS_USER_EMAIL}
      WORDPRESS_USER_PASSWORD: ${WORDPRESS_USER_PASSWORD}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}

  mariadb: 
    build: "./requirements/mariadb"
    image: mariadb
    container_name: mariadb
    expose:
      - "3306"
    networks:
      - backend
    # no ports because we do not want to expose it to host
    volumes:
      - wordpress-data:/var/lib/mysql  # named volume - change to bind mount !
    restart: "on-failure"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  adminer:
      build: ./requirements/bonus/adminer
      image: adminer
      container_name: adminer
      restart: always
      ports: 
        - "8080:8080"
      depends_on:
        - mariadb
      networks:
        - backend

volumes:
  wordpress-site:
  wordpress-data:

# blocks can be empty if we want the default config, compose will create them automatically
networks: # 2 networks for better security
  frontend: # only for nginx and external requests
    driver: bridge
  backend: # connects mariadb+wp(+nginx) - now seems pointless, but networks may grow - this keeps mariadb isolated from other possible frontend containers
    driver: bridge