#TODO: entrypoint is maybe allowed
services:
  nginx:
    build: "./requirements/nginx"
    image: nginx
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - "443:443"
      # - "81:80"
    volumes:
      - wordpress-site:/var/www/html:ro # read-only
      - ${DATA_DIR}/.keys:/etc/ssl:ro # mount keys instead of copying so they are not baked into the image
    restart: unless-stopped

  wordpress:
    build: "./requirements/wordpress"
    image: wordpress
    expose:
      - "9000"
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - wordpress-site:/var/www/html
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WORDPRESS_USER: ${WORDPRESS_USER}
      WORDPRESS_USER_EMAIL: ${WORDPRESS_USER_EMAIL}
      WORDPRESS_USER_PASSWORD: ${WORDPRESS_USER_PASSWORD}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WP_REDIS_HOST: redis
      WP_REDIS_PORT: 6379
      WP_REDIS_PASSWORD: ${REDIS_PASSWORD}

  mariadb: 
    build: "./requirements/mariadb"
    image: mariadb
    expose:
      - "3306"
    networks:
      - inception
    volumes:
      - wordpress-data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "--silent"]
      interval: 5s
      timeout: 5s
      retries: 10

  # bonus:
  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    restart: unless-stopped
    ports: 
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - inception

  ftp:
    build: ./requirements/bonus/ftp
    image: ftp
    restart: unless-stopped
    ports: 
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - wordpress-site:/var/www/html
    networks:
      - inception  
    environment:
      FTP_USER: ${FTP_USER}
      FTP_PASSWORD: ${FTP_PASSWORD}

  redis:
    build: ./requirements/bonus/redis
    image: redis
    ports:
      - 6379:6379
    networks:
      - inception
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  cadvisor:
    build: ./requirements/bonus/cadvisor
    image: cadvisor
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - inception
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro # kernel info incl. cgroups with resource information as CPU usage, memory usage, memory limits, and network information
      - /var/lib/docker:/var/lib/docker:ro # Docker containers and their metadata

  static:
    build: "./requirements/bonus/static"
    image: static
    networks:
      - inception
    ports:
      - "81:80"
    restart: unless-stopped

# named volumes backed by a specific host directories
volumes:
  wordpress-site:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/wordpress-site

  wordpress-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/wordpress-data

networks:
  inception:
    driver: bridge