version: "3.9"

services:
  nginx:
    build: "./requirements/nginx"
    image: nginx
    container_name: nginx
    networks:
      - backend
    depends_on:
      - wordpress
    ports:
      - "443:443" # only expose this to outside world since we have to get requests from internet
    volumes:
      - wordpress-site:/var/www/html
      - ./requirements/nginx/conf:/etc/nginx/conf.d # bind directory with nginx conf file on host to nginx/conf.d on container, as it should always contain the current conf file
      - ./.keys/ssl:/etc/ssl
    restart: "on-failure"

  wordpress:
    build: "./requirements/wordpress"
    image: wordpress
    container_name: wordpress
    expose:
      - "9000"
    networks:
      - backend
    depends_on:
      - mariadb
    # no ports because we do not want to expose it to host
    volumes:
      - wordpress-site:/var/www/html # bind mount
    restart: "on-failure"
    environment:
      WORDPRESS_DB_HOST: mariadb:${DB_PORT}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WORDPRESS_USER: ${WORDPRESS_USER}
      WORDPRESS_USER_EMAIL: ${WORDPRESS_USER_EMAIL}
      WORDPRESS_USER_PASSWORD: ${WORDPRESS_USER_PASSWORD}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WP_REDIS_HOST: redis
      WP_REDIS_PORT: 6379
      WP_REDIS_PASSWORD: ${REDIS_PASSWORD}

  mariadb: 
    build: "./requirements/mariadb"
    image: mariadb
    container_name: mariadb
    expose:
      - "3306"
    networks:
      - backend
    # no ports because we do not want to expose it to host
    volumes:
      - wordpress-data:/var/lib/mysql  # named volume - change to bind mount !
    restart: "on-failure"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    container_name: adminer
    restart: "on-failure"
    ports: 
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - backend

  ftp:
    build: ./requirements/bonus/ftp
    image: ftp
    container_name: ftp
    restart: "on-failure"
    ports: 
      - "21:21"
      - "30000-30009:30000-30009"
    depends_on:
      - wordpress
    volumes:
      - wordpress-site:/var/www/html
    networks:
      - backend  
    environment:
      FTP_USER: ${WORDPRESS_ADMIN_USER}
      FTP_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      DOMAIN_NAME: ${DOMAIN_NAME}

  redis:
    build: ./requirements/bonus/redis
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - backend
    restart: on-failure
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

volumes:
  wordpress-site:
  wordpress-data:

# blocks can be empty if we want the default config, compose will create them automatically
networks:
  backend:
    driver: bridge